// sudoku - Offline Sudoku Game
// Copyright (C) 2025-2026 Alexander Bendlin (darkstar79)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include "../core/i_clipboard_provider.h"
#include "../core/i_game_validator.h"
#include "../core/i_puzzle_generator.h"
#include "../core/i_save_manager.h"
#include "../core/i_settings_manager.h"
#include "../core/i_statistics_manager.h"
#include "../core/i_sudoku_solver.h"
#include "../core/observable.h"
#include "../core/puzzle_analyzer.h"
#include "../model/game_state.h"
#include "core/rating_version.h"
#include "core/solve_step.h"
#include "core/solving_technique.h"

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <fmt/base.h>
#include <fmt/format.h>

namespace sudoku::core {
struct TrainingHint;  // Forward declaration (defined in training_hints.h)
}  // namespace sudoku::core

namespace sudoku::viewmodel {

/// Input mode for number keys on the game board
enum class InputMode : std::uint8_t {
    Normal,      ///< Number keys place values
    Notes,       ///< Number keys toggle pencil marks
    Color,       ///< Number keys apply analysis colors (1-6)
    EditGivens,  ///< Number keys lay down "given" clue cells for an imported puzzle (I-2)
};

/// Size of the free-form analysis color palette (valid colors are 1..kColorPaletteSize).
/// A domain value, not board geometry — there are six palette entries (see SudokuBoardColors).
inline constexpr int kColorPaletteSize = 6;

/// Hint budget used when no ISettingsManager is injected. Lives here rather than in the hints
/// translation unit because the restore path also needs it, to clamp a save's hints_used.
inline constexpr int kDefaultMaxHints = 10;

/// Commands that can be executed from the UI
enum class GameCommand : std::uint8_t {
    NewGame,
    SaveGame,
    LoadGame,
    Undo,
    Redo,
    GetHint,
    ValidateBoard,
    PauseGame,
    ResumeGame,
    ResetGame,
    ShowStatistics,
    ToggleInputMode,
    ClearNotes,
    GetCoachingHint,
    CheckCoachingAnswer,
    ApplyCoachingStep
};

/// Optional arguments for the parameterized GameCommand verbs.
///
/// Parameterless verbs (Undo, PauseGame, ...) ignore every field and can be dispatched with
/// `executeCommand(verb)` via the default-constructed args. Parameterized verbs read exactly
/// one field: NewGame → difficulty, SaveGame → name, LoadGame → save_id. Use the named
/// factories so each call site sets exactly the field its verb consumes.
struct GameCommandArgs {
    std::optional<core::Difficulty> difficulty;  ///< NewGame: target difficulty (falls back to current)
    std::string name;                            ///< SaveGame: save name (empty = autogenerated)
    std::string save_id;                         ///< LoadGame: identifier of the save to restore

    [[nodiscard]] static GameCommandArgs newGame(core::Difficulty difficulty) {
        return {.difficulty = difficulty, .name = {}, .save_id = {}};
    }
    [[nodiscard]] static GameCommandArgs save(std::string name) {
        return {.difficulty = std::nullopt, .name = std::move(name), .save_id = {}};
    }
    [[nodiscard]] static GameCommandArgs load(std::string save_id) {
        return {.difficulty = std::nullopt, .name = {}, .save_id = std::move(save_id)};
    }
};

/// UI state information
struct UIState {
    bool is_game_active{false};
    bool is_paused{false};
    bool is_complete{false};
    InputMode input_mode{InputMode::Normal};
    bool show_conflicts{true};
    bool show_hints{true};
    bool notes_filled{false};
    std::string status_message;
    std::string time_display;
    double puzzle_rating{0.0};                   // Sudoku Explainer rating (SE 1.0-12.0 scale)
    std::vector<std::string> puzzle_techniques;  // Technique names required to solve puzzle

    bool operator==(const UIState& other) const = default;
};

/// Statistics display data
struct StatsDisplay {
    int64_t games_played{0};
    int64_t games_completed{0};
    double completion_rate{0.0};
    std::string best_time;
    std::string average_time;
    int64_t current_streak{0};
    int64_t best_streak{0};

    bool operator==(const StatsDisplay& other) const = default;
};

/// Phase of the coaching hint workflow
enum class CoachingPhase : uint8_t {
    Hinting,  ///< Levels 1-3: progressive hints
    TryIt     ///< Post-L3: user attempts the step, board edits allowed
};

/// Progressive coaching hint state (3 levels of help + TryIt phase)
struct CoachingState {
    bool active{false};
    CoachingPhase phase{CoachingPhase::Hinting};  ///< Current coaching phase
    int level{0};                                 ///< 0=inactive, 1-3
    int max_level{0};                             ///< Highest level reached (for navigation)
    std::string message;                          ///< Coaching text to display
    std::vector<core::CellHighlight> highlights;  ///< Cells to highlight on board with roles
    core::SolvingTechnique technique{};           ///< Current technique being coached
    bool check_submitted{false};                  ///< True after Check pressed (for feedback display)

    bool operator==(const CoachingState& other) const = default;
};

/// Main ViewModel for the Sudoku game following MVVM pattern
class GameViewModel {
public:
    /// Constructor with dependency injection
    GameViewModel(std::shared_ptr<core::IGameValidator> validator, std::shared_ptr<core::IPuzzleGenerator> generator,
                  std::shared_ptr<core::ISudokuSolver> solver, std::shared_ptr<core::IStatisticsManager> stats_manager,
                  std::shared_ptr<core::ISaveManager> save_manager,
                  std::shared_ptr<core::ISettingsManager> settings_manager = nullptr,
                  std::shared_ptr<core::IPuzzleAnalyzer> analyzer = nullptr,
                  std::shared_ptr<core::IClipboardProvider> clipboard = nullptr);

    ~GameViewModel() = default;
    GameViewModel(const GameViewModel&) = delete;
    GameViewModel& operator=(const GameViewModel&) = delete;
    GameViewModel(GameViewModel&&) = delete;
    GameViewModel& operator=(GameViewModel&&) = delete;

    // Observable properties for UI binding
    // Public per MVVM convention: View subscribes and reads, only ViewModel
    // methods mutate. Encapsulation is enforced by convention, not the type system.
    core::Observable<model::GameState> gameState;
    core::Observable<UIState> uiState;
    core::Observable<StatsDisplay> statistics;
    core::Observable<std::string> errorMessage;
    core::Observable<std::string> hintMessage;      // Educational hint explanation
    core::Observable<CoachingState> coachingState;  // Progressive coaching hint state

    // Technique formatting (public for testability)
    [[nodiscard]] std::vector<std::string> formatTechniques(const std::set<core::SolvingTechnique>& techniques,
                                                            bool requires_backtracking) const;

    // Game operations
    void startNewGame(core::Difficulty difficulty);
    void resetGame();
    void loadGame(const std::string& save_id);
    void restoreGameState(const core::SavedGame& saved_game);
    [[nodiscard]] bool saveCurrentGame(const std::string& name = "");
    void autoSave();

    /// Pause the running game's timer (no-op if no game is active).
    void pauseGame();
    /// Resume a paused game's timer (no-op if there is no paused, incomplete game).
    void resumeGame();
    /// Clear every pencil mark on the board.
    void clearNotes();
    /// Report board validity to the user (conflicts / wrong placements) via the error/status
    /// channels and refresh conflict highlighting. Unlike checkSolution(), never advances the game.
    void validateBoard();

    // Board interactions
    void enterNumber(const core::Position& pos, int number);
    void enterNote(const core::Position& pos, int number);
    void clearCell(const core::Position& pos);

    /// Clear every pencil mark in a single cell (the Shift+Delete shortcut). Reuses the
    /// undoable note-removal path; no-op on given or filled cells, since pencil marks only
    /// ever exist on empty cells.
    void clearCellNotes(const core::Position& pos);

    /// Mode-aware number input: validates and routes to enterNumber/enterNote/colorCell.
    /// `override_layer` forces a specific layer regardless of the active InputMode
    /// (Ctrl→Normal/value, Shift→Notes/pencil, Alt→Color); std::nullopt uses the active
    /// mode (the regression-safe default). Overrides are no-ops in EditGivens.
    void handleNumberInput(const core::Position& pos, int number,
                           std::optional<InputMode> override_layer = std::nullopt);

    // Analysis cell coloring (ephemeral, not saved/undoable)
    void colorCell(const core::Position& pos, uint8_t color_index);
    void clearAllCellColors();

    // Position analysis — finds all applicable strategies for the current board state
    struct AnalysisResult {
        core::BoardData board;
        core::BoardData given_board;
        std::vector<uint16_t> candidate_masks;
        std::vector<core::SolveStep> applicable_steps;
    };
    [[nodiscard]] std::optional<AnalysisResult> analyzePosition() const;

    // Game commands
    void executeCommand(GameCommand command, const GameCommandArgs& args = {});
    [[nodiscard]] bool canExecuteCommand(GameCommand command) const;

    // Undo/Redo operations
    void undo();
    void redo();
    void undoToLastValid();
    [[nodiscard]] bool canUndo() const;
    [[nodiscard]] bool canRedo() const;

    // Hint system
    void getHint(std::optional<core::Position> pos);
    [[nodiscard]] int getHintCount() const;

    /// Learning-mode lookup (L-D): finds the next step that uses a specific technique and
    /// publishes its explanation via hintMessage. Sets errorMessage instead if the technique
    /// does not apply or is the Backtracking sentinel. Does NOT consume a hint credit — this
    /// is an exploratory action, not the standard hint flow.
    void findStepByTechnique(core::SolvingTechnique technique);

    /// Replaces the current game state with a puzzle parsed from `input`. Runs the analyzer
    /// pipeline (parse → validate → uniqueness → score) and sets the new game's origin to
    /// PuzzleOrigin::ImportedString. On any failure (parse / validation conflict / multiple
    /// solutions / no analyzer wired), publishes errorMessage and leaves state untouched.
    /// Scoring timeout is swallowed silently — the import still succeeds and rating stays at
    /// the unknown default.
    void importPuzzleFromString(std::string_view input);

    /// Where the current puzzle came from. Tracked at runtime so saveCurrentGame and autoSave
    /// can persist it via SavedGame.origin (added in PR3).
    [[nodiscard]] core::PuzzleOrigin getCurrentPuzzleOrigin() const;

    /// Edit-mode entry point (I-2). Clears the board and switches InputMode to EditGivens.
    /// The View should route digit input to setEditModeGiven while in this mode.
    /// Per plan: no mid-edit validation (pre-mortem #5) — only at commit time.
    void enterEditMode();

    /// Place (or clear, with value == 0) a "given" cell while in EditGivens mode. No-op if
    /// the current input mode is not EditGivens. Does not validate — invalid boards are
    /// caught at commit time, allowing the user to fix conflicts before committing.
    void setEditModeGiven(const core::Position& pos, int value);

    /// Commits the edit-mode board as a new game. Runs validate + checkUniqueness + score via
    /// the analyzer; on success, locks the givens in, switches InputMode to Normal, and sets
    /// origin to ImportedEditMode. On failure, publishes errorMessage and stays in edit mode
    /// so the user can fix the issue. Scoring timeout is swallowed silently — the commit
    /// still succeeds and rating stays at the unknown default.
    void commitEditedPuzzle();

    /// Serializes the current puzzle's GIVENS-only state via IPuzzleAnalyzer::serializeToString
    /// and writes the resulting 81-character string to the clipboard (pre-mortem #14 — the
    /// export companion to import). No-op if no clipboard or analyzer is wired.
    void exportPuzzleAsString();

    // Coaching hint system (progressive 3-level help + TryIt phase)
    void requestCoachingHint();
    void navigateCoachingLevel(int direction);
    void dismissCoaching();
    [[nodiscard]] bool isCoachingActive() const;
    void checkCoachingAnswer();
    void applyCoachingStep();

    // Game state queries
    [[nodiscard]] bool isGameActive() const;
    /// True if the board has structural conflicts (row/col/box duplicates) or, when a solution is
    /// known, any non-given cell whose value differs from the solution. Notes never count — a
    /// pencil-mark contradiction is not a board error. Drives undoToLastValid.
    [[nodiscard]] bool hasBoardErrors() const;
    [[nodiscard]] bool isGameComplete() const;
    [[nodiscard]] bool isGamePaused() const;
    [[nodiscard]] bool isGameStateDirty() const;
    [[nodiscard]] std::string getFormattedTime() const;
    [[nodiscard]] int getMoveCount() const;
    [[nodiscard]] int getMistakeCount() const;
    void checkSolution();

    // Settings and preferences
    void setInputMode(InputMode mode);
    void cycleInputMode();
    [[nodiscard]] InputMode getInputMode() const;
    void setShowConflicts(bool show);
    void setShowHints(bool show);
    void fillNotes();

    /// Enable/disable the color input layer (story 8-21). Disabling drops Color out of the Space
    /// cycle, makes every color entry point inert, leaves Color mode, and clears existing colors —
    /// colors are ephemeral, so nothing persisted is lost.
    void setColoringEnabled(bool enabled);
    [[nodiscard]] bool isColoringEnabled() const;

    // Statistics
    void refreshStatistics();
    void exportStatistics(const std::string& file_path);

    // Data accessors for dialogs (non-observable snapshots)
    [[nodiscard]] std::vector<core::SavedGame> getSaveList() const;
    [[nodiscard]] std::optional<core::AggregateStats> getAggregateStats() const;
    [[nodiscard]] std::vector<core::GameStats> getRecentGames(int count = 20) const;

    // Time formatting utility
    [[nodiscard]] static std::string formatDuration(std::chrono::milliseconds time);

    // Session history management
    void deleteSessionHistory();
    void flushStatsSessions();

    /// True when the stored session history could not be read (e.g. encrypted on a
    /// different system, or partially written). The file is preserved, not overwritten.
    [[nodiscard]] bool hasUnreadableSessionHistory() const;

    /// Archive an unreadable session-history file aside ("*.corrupt-<timestamp>") so a
    /// fresh history can be started without destroying the original bytes.
    /// @return The archive path on success; std::nullopt on failure (errorMessage is set).
    [[nodiscard]] std::optional<std::string> archiveUnreadableSessionHistory();

    // CSV Export
    [[nodiscard]] std::expected<void, std::string> exportAggregateStatsCsv() const;
    [[nodiscard]] std::expected<void, std::string> exportGameSessionsCsv() const;

    // Error handling
    void clearErrorMessage();
    [[nodiscard]] bool hasError() const;

private:
    // Dependencies
    std::shared_ptr<core::IGameValidator> validator_;
    std::shared_ptr<core::IPuzzleGenerator> generator_;
    std::shared_ptr<core::ISudokuSolver> solver_;
    std::shared_ptr<core::IStatisticsManager> stats_manager_;
    std::shared_ptr<core::ISaveManager> save_manager_;
    std::shared_ptr<core::ISettingsManager> settings_manager_;
    std::shared_ptr<core::IPuzzleAnalyzer> analyzer_;      // Optional — only the import/analyze flows need it.
    std::shared_ptr<core::IClipboardProvider> clipboard_;  // Optional — only export needs it.

    /// Tracks where the current puzzle came from so save/auto-save persist origin via SavedGame.
    core::PuzzleOrigin current_puzzle_origin_{core::PuzzleOrigin::Generated};

    // Internal state
    uint64_t current_game_session_{0};
    std::vector<core::Move> move_history_;
    int move_history_index_{-1};
    int last_valid_state_index_{-1};  // Index of last conflict-free board state
    /// True while move_history_ is a complete forward log back to the original puzzle. Every path
    /// that starts a game from a known-original board (new, reset, edit-mode commit, import) clears
    /// the log and sets this true; the restore path inherits the incoming save's flag, so a game
    /// resumed from a history-less auto-save stays marked incomplete for as long as it lives — and
    /// so does any manual save taken from it (story 8.16 / D2, SavedGame::history_complete).
    bool move_history_complete_{true};
    bool auto_save_enabled_{true};
    // Gates the color input layer (story 8-21). The {true} default is load-bearing — every
    // tests/unit fixture builds this ViewModel with settings_manager == nullptr (AC2).
    bool coloring_enabled_{true};
    double current_puzzle_rating_{0.0};  // Rating of current puzzle (SE scale)
    std::set<core::SolvingTechnique> current_puzzle_techniques_;
    bool current_puzzle_requires_backtracking_{false};
    // Rating-model version that produced current_puzzle_rating_. Stamped to the current model
    // (RATING_MODEL_VERSION) whenever this build freshly rates a puzzle, and set to a loaded
    // save's stored version on load — so re-saving a legacy game preserves its older provenance
    // and it stays recognizably stale (the 0b.0 firewall; do not always write the constant).
    int current_puzzle_rating_model_version_{core::RATING_MODEL_VERSION};

    // Private methods
    void validateCurrentBoard();
    void updateUIState();
    void updateTimeDisplay();
    void startGameSession();

    /// Single apply path for persisted settings, invoked from both the constructor's initial apply
    /// and the settingsObservable() callback — so a new setting cannot be wired into one path and
    /// silently omitted from the other (story 8-19, mirrors MainWindow::applySettings()).
    void applySettings(const core::Settings& s);

    /// Copies the active session's moves/hints/mistakes onto an outgoing save. Leaves the
    /// defaults at 0 when no session exists. Shared by saveCurrentGame() and autoSave().
    void applyProgressCounters(core::SavedGame& saved_game) const;

    /// Starts the statistics session for a game being restored and seeds it with the save's
    /// carried-over progress. Must be called only after current_puzzle_rating_ has been restored,
    /// or the recorded session carries rating 0.0.
    void startRestoredSession(const core::SavedGame& saved_game);

    /// Rebuilds the board/notes/hint-revealed layers of a GameState from a save: loads the
    /// original puzzle, overlays the user's entered values onto non-given cells, then restores
    /// notes and hint-revealed markers. Pure construction — does not touch the view model's own
    /// state (clock, move history, etc.), which restoreGameState re-seats afterward.
    [[nodiscard]] static model::GameState buildRestoredGameState(const core::SavedGame& saved_game);

    /// Whether a save carries the signature of the "all cells marked given" corruption bug.
    /// Only ever true for MANUAL saves — see the implementation for why auto-saves are exempt.
    [[nodiscard]] static bool isCorruptedManualSave(const core::SavedGame& saved_game);
    void endGameSession(bool completed);

    /// Drops the undo/redo log and marks it complete — the correct state for every path that starts
    /// a game from its own original board (new game, reset, edit-mode entry, edit-mode commit,
    /// import). The restore path does NOT use this: it inherits the incoming save's flag instead.
    ///
    /// One choke point rather than five copies of the same three assignments, so a future start
    /// path cannot reset the log and leave move_history_complete_ stale — which would mark a fresh
    /// game's save as history-less and quietly exempt it from the corruption guard (story 8.16).
    void resetMoveHistory();

    void recordMove(const core::Move& move, bool is_mistake = false);
    /// First application of a freshly-created move (forward edit). Runs the note-cleanup and
    /// records the exact peer-note delta into `move` so revert/redo replay it verbatim — no
    /// re-derivation against the live board (Story 6.1 / #76).
    void applyMoveCapture(core::Move& move);
    /// Re-application of an already-recorded move (redo). Replays the stored peer-note delta
    /// instead of recomputing it, keeping cleanup and restore true inverses.
    void applyMoveReplay(const core::Move& move);
    void revertMove(const core::Move& move);
    /// Strips `number` from the pencil marks of every empty peer (row/col/box) that actually
    /// holds it, returning exactly those peer positions so the placement can be inverted.
    [[nodiscard]] static std::vector<core::Position> cleanupConflictingNotes(model::GameState& state,
                                                                             const core::Position& pos, int number);
    /// Forward inverse of cleanup, used when a placed value is cleared: re-adds `value` as a
    /// pencil mark to every empty peer where it is now a legal candidate and does not already
    /// hold it. Returns the peers it added to, so undoing the clear re-strips exactly those.
    [[nodiscard]] static std::vector<core::Position>
    restorePeerNotesForClearedValue(model::GameState& state, const core::Position& pos, int value);
    /// Faithful inverse for clearing a placed value (Story 6.1 / #76, review 2026-06-14): reuse the
    /// originating PlaceNumber/PlaceHint move's recorded `peer_note_delta` (the peers the value was
    /// actually stripped from), re-adding it only to peers still empty — so a candidate the player
    /// manually eliminated is never resurrected. Falls back to `restorePeerNotesForClearedValue`
    /// re-derivation only when no placement move is in history (loaded saves / truncated history).
    /// Mutates `state` and returns the peers re-added to (the clear move's delta).
    [[nodiscard]] std::vector<core::Position> restoreClearedValueNotes(model::GameState& state,
                                                                       const core::Position& pos, int value);
    /// Drop any redo tail (moves beyond the cursor) and clamp the last-valid index. Called when
    /// notes are mutated outside the move model (fill/clear-all) so a pending redo cannot replay a
    /// stored delta against a now-stale note state (Story 6.1 review 2026-06-14).
    void invalidateRedoTail();
    void checkGameCompletion();
    void handleError(std::string_view message);
    [[nodiscard]] static std::string formatTime(std::chrono::milliseconds time);
    void autoSaveIfNeeded();
    void recomputeAutoNotes();
    void clearAllNotes();
    void updateConflictHighlighting();

    // Hint system helpers
    [[nodiscard]] std::string formatHintExplanation(const core::SolveStep& step) const;
    [[nodiscard]] std::string statisticsErrorToString(core::StatisticsError error) const;

    /// Runs analyzer_->scoreDifficulty against `board` within a 1-second budget and writes the
    /// result to current_puzzle_rating_ / current_puzzle_techniques_ /
    /// current_puzzle_requires_backtracking_. On Timeout, leaves those fields untouched (caller
    /// is expected to seed them to the unknown-defaults beforehand). NoSolution / InvalidInput
    /// post-validation indicate a solver/validator disagreement and are logged as warnings.
    /// Used by importPuzzleFromString and commitEditedPuzzle to auto-rate user-supplied
    /// puzzles after the uniqueness check passes. No-op if no analyzer is wired.
    void applyDifficultyScore(const core::BoardData& board);

    // Coaching hint state — step and snapshot are always set/cleared together
    struct CoachingContext {
        core::SolveStep step;
        model::GameState snapshot;  ///< Board state when TryIt phase started
    };
    std::optional<CoachingContext> coaching_context_;
    void resetCoachingState();
    void resetCoachingIfNotTryIt();
    [[nodiscard]] std::string buildLevel1Message(const core::TrainingHint& hint, const core::SolveStep& step) const;

    // Statistics helpers
    [[nodiscard]] StatsDisplay createStatsDisplay(const core::AggregateStats& stats) const;
    void updateStatisticsDisplay();

    /// Subscription to settings_manager_->settingsObservable(). Declared LAST so it is destroyed
    /// FIRST (reverse declaration order) — settings_manager_ is a shared_ptr owned by DIContainer
    /// and outlives the ViewModel, so an un-torn-down subscription would leave applySettings()'s
    /// callback dereferencing members (uiState, stats_manager_) that have already been destroyed.
    core::CompositeObserver settings_observer_;
};

}  // namespace sudoku::viewmodel